-- 코드를 입력하세요
SELECT  B.AUTHOR_ID
        ,A.AUTHOR_NAME
        ,B.CATEGORY
        ,SUM(B.PRICE*S.SALES) AS TOTAL_SALES
  FROM  BOOK_SALES AS S
 INNER
  JOIN  BOOK AS B
    ON  S.BOOK_ID = B.BOOK_ID
  LEFT
  JOIN  AUTHOR AS A
    ON  B.AUTHOR_ID = A.AUTHOR_ID
 WHERE  MONTH(S.SALES_DATE) = 01
 GROUP
    BY  AUTHOR_ID, CATEGORY
 ORDER
    BY  AUTHOR_ID, CATEGORY DESC  
;